baseURL = "https://blog.askin.ws"
languageCode = "tr-TR"
title = "Aşkın Özgür"

theme = "beautifulhugo"
disqusShortname = "askin-ozgurun-web-gunlugu"

defaultContentLanguage = "tr"

summaryLength = 100

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Anasayfa"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Hakkımda"
    url = "about/"
    weight = 11

  [[menu.main]]
    name = "İbretlik Tavsiyeler"
    url = "ibretlik-tavsiyeler/"
    weight = 12

  [[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 21


[Params]
  homeTitle = "Aşkın Özgür"
  subtitle = "Aşkın Özgür'ün Web Günlüğü"
  mainSections = ["blog"]
  logo = "uploads/avatar.png" # Expecting square dimensions
  favicon = "uploads/avatar.png"
  # dateFormat = "January 2, 2006"
  dateFormat = "2006/01/02"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true

# [[Params.bigimg]]
#  src = "img/path.jpg"
#  desc = "Triangle"

[Author]
  name = "Aşkın Özgür"
  website = "https://askin.ws"
  email = "askin@askin.ws"
  facebook = "askinyollu"
  github = "askin"
  gitlab = "askinozgur"
  bitbucket = "askin"
  twitter = "kelebeks"
  linkedin = "askin.yollu"
  spotify = "kelebex"
  telegram = "kelebeks"

  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # 500px = "username"
  # codepen = "username"
  # mastodon = "url"
  # kaggle = "username"
  # weibo = "username"
  # slack = "username"
